const frutas = [
  ["apple", "manzana"],
  ["banana", "plátano"],
  ["pineapple", "piña"],
  ["lime", "lima - limon verde"],
  ["pear", "pera"],
  ["plantain", "plátano verde"],
  ["grape", "uva"],
  ["orange", "naranja"],
  ["lemon", "lima"],
  ["grapefruit", "toronja - pomelo"],
  ["strawberry", "fresa"],
  ["raspberry", "frambuesa"],
  ["blackberry", "mora"],
  ["blueberry", "arándano"],
  ["cranberry", "arándano rojo"],
  ["kiwi", "kiwi"],
  ["watermelon", "sandia"],
  ["cantaloupe", "cantalupo"],
  ["cucumber", "pepino"],
  ["papaya", "papaya"],
  ["mango", "mango"],
  ["coconut", "coco"],
  ["passion-fruit", "maracuyá"],
  ["pomegranate", "granada"],
  ["peach", "durazno - melocotón"],
  ["nectarine", "nectarina"],
  ["apricot", "damasco - albaricoque"],
  ["avocado", "palta - aguacate"],
  ["tomato", "tomate - jitomate"],
];

const animalesDomestico = [
  ["dog", "perro"],
  ["cat", "gato"],
  ["pig", "cerdo"],
  ["cow", "vaca"],
  ["hen", "gallina"],
  ["rooster", "gallo"],
  ["chicken", "pollo"],
  ["duck", "pato"],
  ["turkey", "pavo"],
  ["sheep", "oveja"],
  ["goat", "cabra"],
  ["horse", "caballo"],
  ["donkey", "burro"],
  ["mouse", "ratón"],
  ["rat", "rata"],
  ["rabbit", "conejo"],
  ["goose", "ganso"],
  ["parrot", "loro"],
];

const alura = [
  ["alura", "Donde aprender es divertido"],
  ["niño", "la alegria del hogar"],
  ["afinidad", "Parecido, relación o analogía de una cosa con otra."],
  ["youtube", "Un lugar para ver videos"],
  ["programar", "Pensar para tomar una accion"],
  ["oracle", "Propietaria de JAVA"],
];

const vegetales = [
  ["artichoke", "alcachofa"],
  ["asparagos", "espárrago"],
  ["beans", "frijoles - porotos"],
  ["beet", "remolacha"],
  ["bell-pepper", "pimenton - morron"],
  ["broccoli", "brocoli"],
  ["cabbage", "repollo"],
  ["carrot", "zanahoria"],
  ["cauliflower", "coliflor"],
  ["celery", "apio"],
  ["chilly", "aji picante"],
  ["cucumber", "pepino"],
  ["eggplant", "berenjena"],
  ["garlic", "ajo"],
  ["lettuce", "lechuga"],
  ["mushrroms", "hongos"],
  ["onio", "cebolla"],
  ["parsley", "perejil"],
  ["peas", "arvejas"],
  ["potato", "papa - patata"],
  ["pumpkin", "calabaza"],
  ["spinach", "espinaca"],
  ["sweet-potato", "camote"],
  ["tomato", "tomate"],
  ["corn", "mais"],
];

const familia = [
  ["grandfather", "abuelo"],
  ["grandmother", "abuela"],
  ["brother", "hermano"],
  ["sister", "hermana"],
  ["father", "padre"],
  ["husband", "esposo"],
  ["mother", "madre"],
  ["wife", "esposa"],
  ["daughter", "hija"],
  ["son", "hijo"],
  ["daughter", "hija"],
  ["grandson", "nieto"],
  ["granddaughter", "nieta"],
  ["uncle", "tío"],
  ["aunt", "tía"],
  ["cousin", "primo - prima"],
  ["nephew", "sobrino"],
  ["niece", "sobrina"],
  ["father in law", "suegro"],
  ["mother in law", "suegra"],
  ["son in law", "nuera"],
  ["daughter in law", "nuera"],
  ["brother in law", "cuñado"],
  ["sister in law", "cuñada"],
];

const partesCuerpo = [
  ["mouth", "boca"],
  ["arm", "brazo"],
  ["head", "cabeza"],
  ["face", "cara"],
  ["elbow", "codo"],
  ["heart", "corazon"],
  ["fingers", "dedos"],
  ["tooth", "diente"],
  ["teeth", "dientes"],
  ["back", "espalda"],
  ["lips", "labios"],
  ["hand", "mano"],
  ["nose", "nariz"],
  ["eyes", "ojos"],
  ["ears", "orejas"],
  ["foot", "pie"],
  ["leg", "pierna"],
  ["feet", "pies"],
  ["knee", "rodilla"],
  ["nails", "uñas"],
  ["hair", "cabello"],
  ["hips", "caderas"],
  ["eyebrows", "sejas"],
  ["brain", "cerebro"],
  ["waist", "cintura"],
  ["rib", "costilla"],
  ["neck", "cuello"],
  ["toes", "dedos de los pies"],
  ["stomach", "estomago"],
  ["forhead", "frente"],
  ["throat", "garganta"],
  ["tongue", "lengua"],
  ["cheeks", "mejillas"],
  ["skin", "piel"],
  ["ankle", "tobillo"],
  ["shoulder", "brazo"],
  ["blood", "sangre"],
  ["skeleton", "esqueleto"],
];

const numeros = [
  ["one", "uno"],
  ["two", "dos"],
  ["three", "tres"],
  ["four", "cuatro"],
  ["five", "cinco"],
  ["six", "seis"],
  ["seven", "siete"],
  ["eight", "ocho"],
  ["nine", "nueve"],
  ["ten", "diez"],
  ["zero", "cero"],
  ["eleven", "once"],
  ["twelve", "doce"],
  ["thirteen", "trece"],
  ["fourteen", "catorce"],
  ["fifteen", "quince"],
  ["sixteen", "dieciséis"],
  ["seventeen", "diecisiete"],
  ["eighteen", "diecinueve"],
  ["nineteen", "diecinueve"],
  ["twenty", "veinte"],
  ["thirty", "treinta"],
  ["forty", "cuarenta"],
  ["fifty", "cincuenta"],
  ["sixty", "sesenta"],
  ["seventy", "setenta"],
  ["eighty", "ochenta"],
  ["ninety", "noventa"],
  ["onehundred", "cien"],
];

const colores = [
  ["yellow", "amarillo"],
  ["pink", "rosado"],
  ["white", "blanco"],
  ["purple", "morado"],
  ["blue", "azul"],
  ["gray", "gris"],
  ["brown", "marron"],
  ["orange", "naranja"],
  ["green", "verde"],
  ["red", "rojo"],
  ["black", "negro"],
  ["golden", "dorado"],
  ["cream", "crema"],
  ["chestnut", "castaña"],
  ["skyblue", "celeste"],
  ["turquoise", "turquesa"],
  ["navyblue", "azul"],
  ["lightgreen", "verde claro"],
  ["darkgreen", "verde oscuro"],
];

const diasSemana = [
  ["sunday", "domingo"],
  ["monday", "lunes"],
  ["tuesday", "martes"],
  ["wednesday", "miercoles"],
  ["thursday", "jueves"],
  ["friday", "viernes"],
  ["saturday", "sabado"],
];

const vestimenta = [
  ["boots", "botas"],
  ["briefs", "calzoncillos"],
  ["belt", "cinturon"],
  ["cap", "gorra"],
  ["coat", "abrigo"],
  ["gloves", "guantes"],
  ["hat", "sonbrero"],
  ["jeans", "pantalon vaquero"],
  ["jacket", "chaqueta"],
  ["overcoat", "abrigo - sobretodo"],
  ["pullover", "jersey - sueter de lana"],
  ["pajamas", "pijama"],
  ["pants", "pantalon"],
  ["scarf", "vufanda"],
  ["coat", "abrigo"],
  ["shorts", "pantalon corto"],
  ["shoes", "zapato"],
  ["shirt", "camisa"],
  ["sneakers", "zapatillas"],
  ["sock", "calcetin"],
  ["suit", "traje"],
  ["sweater", "suéter"],
  ["sweatshirt", "sudadera"],
  ["tshirt", "polera"],
  ["tie", "corbata"],
  ["tennisshoes", "calzado de tenis"],
  ["trouse", "pantalon"],
  ["underwear", "ropa interio"],
  ["bra", "sostén"],
];
